src/main/java/com/tr/aksigorta/denetimtaleptakip/model/BusinessProcessType.java
package com.tr.aksigorta.denetimtaleptakip.model;

import com.google.common.collect.Lists;
import com.google.common.collect.Sets;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.List;
import java.util.Set;

/**
 * User: mhazer
 * Date: 8/19/12
 * Time: 4:58 PM
 */
@Entity
@Table(name = "DT_ID_BUSINESS_PROC_TABLE")
@Data
@ToString(includeFieldNames = true, callSuper = true, exclude = {"subProcessTypes", "responsibleHeads"})
@EqualsAndHashCode(exclude = {"subProcessTypes", "responsibleHeads"}, callSuper = true)
public class BusinessProcessType extends BaseDefinitionEntity implements Serializable
{
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mainProcess", cascade = CascadeType.ALL)
    @OrderBy("description")
    private Set<BusinessSubProcessType> subProcessTypes = Sets.newHashSet();

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "DT_ID_PROC_RESPONSIBLE_HEADS",
            joinColumns =
            @JoinColumn(name = "PROC_ID", referencedColumnName = "ID"),
            inverseJoinColumns =
            @JoinColumn(name = "USER_ID", referencedColumnName = "ID")
    )
    private Set<User> responsibleHeads = Sets.newHashSet();

    @Transient
    public List<BusinessSubProcessType> subprocessTypesAsList()
    {
        return Lists.newLinkedList(getSubProcessTypes());
    }
    
    @Transient
    public List<User> getResponsibleHeadsAsList()
    {
        return Lists.newLinkedList(getResponsibleHeads());
    }

}

src/main/java/com/tr/aksigorta/denetimtaleptakip/model/Finding.java
package com.tr.aksigorta.denetimtaleptakip.model;

import com.google.common.base.Predicate;
import com.google.common.collect.Iterables;
import com.google.common.collect.Lists;
import com.google.common.collect.Sets;
import com.tr.aksigorta.denetimtaleptakip.controller.util.CalendarUtil;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import org.apache.commons.lang.StringUtils;
import org.hibernate.annotations.Type;
import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;
import org.hibernate.envers.RelationTargetAuditMode;
import org.joda.time.DateTime;
import org.joda.time.LocalDate;

import javax.annotation.Nullable;
import javax.persistence.*;
import javax.persistence.Transient;

import java.beans.*;
import java.io.Serializable;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

/**
 * User: mhazer
 * Date: 8/20/12
 * Time: 11:49 AM
 */
@Table(name = "DT_RT_FINDINGS_TABLE")
@Entity
@Data
@ToString(includeFieldNames = true, callSuper = true, exclude = {"findingActions", "findingResponsibleActions", "auditUser"})
@EqualsAndHashCode(callSuper = true, exclude = {"findingActions", "findingResponsibleActions", "auditUser"})
public class Finding extends BaseEntity implements Serializable {

    @ManyToOne
    @JoinColumn(name = "AUDIT_TYPE")
    private AuditType auditType;

    @ManyToOne
    @JoinColumn(name = "COMPANY_ID")
    private Company company;

    @ManyToOne
    @JoinColumn(name = "BUSINESS_PROC")
    private BusinessProcessType businessProcessType;

    @ManyToOne
    @JoinColumn(name = "BUSINESS_SUB_PROC")
    private BusinessSubProcessType businessSubProcessType;

    @Column(name = "FINDING_NUMBER")
    private String findingNumber;

    @Lob
    private String description;

    @Type(type = "com.tr.aksigorta.denetimtaleptakip.model.PriorityUserType")
    private Priority priority;

    @Lob
    private String detail;

    private String risk;

    @Lob
    private String recommendation;

    @Column(name = "MANAGEMENT_ACTION_PLAN")
    @Lob
    private String managementActionPlan;

    @Column(name = "COMPLETION_DATE")
    private Date completionDate;

    @Column(name = "SEND_EMAIL", columnDefinition = "BIT", length = 1)
    private Boolean sendEmail = Boolean.TRUE;

    @Column(name = "REASON_TO_NOT_SEND_EMAIL")
    @Type(type = "com.tr.aksigorta.denetimtaleptakip.model.EmailReasonUserType")
    private EmailReason reasonToNotSendEmail;

    @Column(name = "COMPLETED", columnDefinition = "BIT", length = 1)
    private Boolean completed = Boolean.FALSE;

    @Column(name = "CONFIRMED", columnDefinition = "BIT", length = 1)
    private Boolean confirmed = Boolean.FALSE;

    @Column(name = "REVISED", columnDefinition = "BIT", length = 1)
    private Boolean revised = Boolean.FALSE;

    @Column(name = "AUDIT_DATE")
    private Date auditDate;
    
    @Temporal(TemporalType.DATE)
    @Column(name = "FINDING_YEAR", length=4)
    private Date findingYear;

    @Column(name = "REVISED_COMPLETION_DATE")
    private Date revisedCompletionDate;
    
    @Column(name = "REPORT_NAME")
    private String reportName;

    @ManyToOne
    @JoinColumn(name = "AUDIT_USER")
    private User auditUser;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "finding", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("changeDate desc")
    private Set<FindingAction> findingActions = Sets.newHashSet();

   
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "finding", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("changeDate desc")
    private Set<FindingResponsibleAction> findingResponsibleActions = Sets.newHashSet();

    public Set<FindingResponsibleAction> getFindingResponsibleActions() {
		return findingResponsibleActions;
	}

	public void setFindingResponsibleActions(Set<FindingResponsibleAction> findingResponsibleActions) {
		this.findingResponsibleActions = findingResponsibleActions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "finding", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("changeDate")
    private Set<FindingFile> findingFiles = Sets.newHashSet();

    @Transient
    public List<FindingAction> findingActionsAsList() {
        return Lists.newLinkedList(getFindingActions());
    }

    @Transient
    public List<FindingResponsibleAction> findingResponsibleActionsAsList() {
        return Lists.newLinkedList(getFindingResponsibleActions());
    }

    @Transient
    public List<FindingFile> findingFilesAsList() {
        return Lists.newLinkedList(getFindingFiles());
    }

    @Transient
    public void adjustFindingActionsForUsers(List<User> actionOwners, List<User> readOnlyActionOwners) {
        addFindingActionsToOwners(actionOwners, false);
        addFindingActionsToOwners(readOnlyActionOwners, true);
        adjustFindingActionsCompletionDates(actionOwners, readOnlyActionOwners);
    }

    @Transient
    public void adjustFindingResponsibleActionsForUser(User responsibleActionOwner) {
        addFindingResponsibleActionsToOwners(responsibleActionOwner);
    }

    private void addFindingActionsToOwners(List<User> actionOwners, boolean readOnly) {
        for (User _actionOwner : actionOwners) {
            if (!isFindingActionExistsForUser(_actionOwner)) {
                FindingAction findingAction = new FindingAction();
                findingAction.setFinding(this);
                findingAction.setActionOwner(_actionOwner);
                findingAction.setReadOnly(readOnly);
                getFindingActions().add(findingAction);
            } else {
                findingActionOfUser(_actionOwner).setReadOnly(readOnly);
            }
        }
    }

    private void addFindingResponsibleActionsToOwners(User responsibleActionOwner) {
        if (!isFindingResponsibleActionExistsForUser(responsibleActionOwner)) {
            FindingResponsibleAction findingResponsibleAction = new FindingResponsibleAction();
            findingResponsibleAction.setFinding(this);
            findingResponsibleAction.setActionOwner(responsibleActionOwner);
            getFindingResponsibleActions().add(findingResponsibleAction);
        }
    }

    @Transient
    public boolean isFindingActionExistsForUser(User _user) {
        for (FindingAction findingAction : getFindingActions()) {
            if (findingAction.getActionOwner().getId().equals(_user.getId())) {
                return true;
            }
        }
        return false;
    }

    @Transient
    public boolean isFindingResponsibleActionExistsForUser(User _user) {
        for (FindingResponsibleAction findingResponsibleAction : getFindingResponsibleActions()) {
            if (findingResponsibleAction.getActionOwner().getId().equals(_user.getId())) {
                return true;
            }
        }
        return false;
    }

    @Transient
    public FindingAction findingActionOfUser(User _user) {
        for (FindingAction findingAction : getFindingActions()) {
            if (findingAction.getActionOwner().getId().equals(_user.getId())) {
                return findingAction;
            }
        }
        return null;
    }

    @Transient
    public FindingResponsibleAction findingResponsibleActionOfUser(User _user) {
        for (FindingResponsibleAction findingResponsibleAction : getFindingResponsibleActions()) {
            if (findingResponsibleAction.getActionOwner().getId().equals(_user.getId())) {
                return findingResponsibleAction;
            }
        }
        return null;
    }

    @Transient
    private void adjustFindingActionsCompletionDates(List<User> actionOwners, List<User> readOnlyActionOwners) {
        for (Iterator<FindingAction> iterator = getFindingActions().iterator(); iterator.hasNext(); ) {
            FindingAction findingAction = iterator.next();
            if (!sendEmail) {
                findingAction.setCompletionPercentage(100);
                setCompleted(Boolean.TRUE);
                findingAction.setActionTaken(StringUtils.EMPTY);
            } else if (findingAction.isReadOnly()) {
                findingAction.setCompletionPercentage(100);
                setReasonToNotSendEmail(null);
                findingAction.setReadOnly(Boolean.TRUE);
                findingAction.setActionTaken("Read Only User");
            } else if (findingAction.getId() == null) {
                setCompleted(Boolean.FALSE);
                setReasonToNotSendEmail(null);
                findingAction.setCompletionPercentage(0);
                findingAction.setActionTaken(StringUtils.EMPTY);
            }
            if (!actionOwners.contains(findingAction.getActionOwner()) && !readOnlyActionOwners.contains(findingAction.getActionOwner())) {
                iterator.remove();
            }
        }
    }

    @Transient
    public Set<FindingAction> retainPersistedFindingActions() {
        return Sets.newHashSet(
                Iterables.filter(getFindingActions(), new Predicate<FindingAction>() {
                    @Override
                    public boolean apply(@Nullable FindingAction findingAction) {
                        return findingAction.getId() != null;
                    }
                }));
    }

    @Transient
    public Set<FindingResponsibleAction> retainPersistedFindingResponsibleActions() {
        return Sets.newHashSet(
                Iterables.filter(getFindingResponsibleActions(), new Predicate<FindingResponsibleAction>() {
                    @Override
                    public boolean apply(@Nullable FindingResponsibleAction findingResponsibleAction) {
                        return findingResponsibleAction.getId() != null;
                    }
                }));
    }

    @Transient
    public Status getStatusOfFinding() {
        if (confirmed) {
            if (completed) {
                return Status.CONFIRMED_COMPLETED;
            } else {

src/main/java/com/tr/aksigorta/denetimtaleptakip/model/User.java
package com.tr.aksigorta.denetimtaleptakip.model;

import com.google.common.collect.Lists;
import com.google.common.collect.Sets;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import org.apache.commons.collections.CollectionUtils;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;
import org.hibernate.envers.RelationTargetAuditMode;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Set;

/**
 * User: dpinar
 * Date: 3/8/17
 * Time: 3:27 PM
 */

@Entity
@Table(name = "dt_id_users_table")
@Data
@ToString(includeFieldNames = true, callSuper = true, exclude = {"findings", "adminUser", "responsibleBusinessTypes", "responsibleBusinessSubTypes"})
@EqualsAndHashCode(callSuper = true, of = {"username"})
@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
public class User extends BaseEntity implements Serializable
{
    @Column(name = "username")
    private String username;
    @Column(name = "email")
    private String email;
    @Column(name = "name_surname")
    private String nameSurname;
    @Column(name = "job_title")
    private String jobTitle;
    @Column(name = "ACTIVE", columnDefinition = "BIT", length = 1)
    private boolean active = true;
    @ManyToOne
    @JoinColumn(name = "ADMIN_USER_ID")
    private User adminUser;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EDIT_DATE")
    private Date editDate;

    @OneToMany(mappedBy = "actionOwner")
    private Set<FindingAction> findings = Sets.newHashSet();

    @ManyToMany(mappedBy = "responsibleHeads", fetch = FetchType.LAZY)
    private Set<BusinessProcessType> responsibleBusinessTypes = Sets.newHashSet();

    @ManyToMany(mappedBy = "responsibleHeads", fetch = FetchType.LAZY)
    private Set<BusinessSubProcessType> responsibleBusinessSubTypes = Sets.newHashSet();

    @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinTable(
            name = "DT_ID_USER_ROLES_TABLE",
            joinColumns =
            @JoinColumn(name = "USER_ID", referencedColumnName = "ID"),
            inverseJoinColumns =
            @JoinColumn(name = "ROLE_ID", referencedColumnName = "ID")
    )
    @Fetch(FetchMode.SUBSELECT)
    @NotAudited
    private Set<Role> roles = Sets.newHashSet();

    @Transient
    public static List<String> usersEmailAddresses(Collection<User> users)
    {
        List<String> emailAddresses = Lists.newArrayList();
        for (User user : users)
        {
        	if(user.isActive())	// kullanıcı aktif ise mail listesine ekle 
        		emailAddresses.add(user.getEmail());
        }
        return emailAddresses;
    }

    @Transient
    public static List<String> usersNamesAndSurnames(Collection<User> users)
    {
        List<String> namesAndSurname = Lists.newArrayList();
        for (User user : users)
        {
            namesAndSurname.add(user.getNameSurname());
        }
        return namesAndSurname;
    }

    @Transient
    public boolean isUserReponsibleOfAnyBusinessType()
    {
        return CollectionUtils.isNotEmpty(getResponsibleBusinessTypes()) || CollectionUtils.isNotEmpty(getResponsibleBusinessSubTypes());
    }

    @Transient
    public boolean hasRole(String roleName)
    {
        for (Role role : getRoles())
        {
            if (role.getName().equals(roleName))
            {
                return true;
            }
        }
        return false;
    }

    @Transient
    public List<Role> getRolesAsList()
    {
        return Lists.newLinkedList(getRoles());
    }

}

src/main/webapp/admin/auditAndBusinessTypesViewAll.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:prime="http://primefaces.org/ui"
                xmlns:util="http://java.sun.com/jsf/composite/components/common"
                template="/WEB-INF/templates/default.xhtml">

    <ui:define name="pageHeader">
        View All Audit, Business and Business Process Types in Once
    </ui:define>

    <ui:define name="mainContent">
        <h:form>
            <prime:commandButton value="Print" type="button" icon="ui-icon-print" style="float:right">
                <prime:printer target="tree"/>
            </prime:commandButton>
            <br />
            <br />
            <prime:treeTable
                    id="tree"
                    value="#{auditBusinessTypeController.rootNode}"
                    var="_node"
                    dynamic="true"
                    cache="false">
                <prime:column headerText="Description">
                    <h:outputText value="#{_node.description}"/>
                </prime:column>
                <prime:column headerText="Responsible Heads">
                    <prime:dataList value="#{_node.responsibleHeadsAsList}" var="_responsible" styleClass="dataList">
                        #{_responsible.nameSurname}
                    </prime:dataList>
                </prime:column>
            </prime:treeTable>
            <br />
            <prime:commandButton value="Print" type="button" icon="ui-icon-print" style="float:right">
                <prime:printer target="tree"/>
            </prime:commandButton>
        </h:form>
    </ui:define>

    <ui:define name="helpContent">
        <b>
        </b>
    </ui:define>

</ui:composition>

src/main/webapp/admin/findingAdmin.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:prime="http://primefaces.org/ui"
                xmlns:util="http://java.sun.com/jsf/composite/components/common"
                template="/WEB-INF/templates/default.xhtml">

    <ui:define name="pageHeader">
        Audit Findings
    </ui:define>

    <ui:define name="mainContent">
        <h:form>
            <util:findingList
                    findings="#{findingAdminController.findingLazyDataModel}"
                    bean="#{findingAdminController}"/>
        </h:form>
    </ui:define>

    <ui:define name="helpContent">
        <b>
            At this page you can view the audit findings that are assigned to you and other users and also view/change status of them
        </b>
    </ui:define>

</ui:composition>

src/main/webapp/admin/findingGraphicalReports.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:prime="http://primefaces.org/ui" xmlns:ice="http://java.sun.com/jsf/html"
                template="/WEB-INF/templates/default.xhtml">

    <ui:define name="pageHeader">
        Finding Graphical Reports
    </ui:define>

    <ui:define name="mainContent">
        <div class="span2 offset3">
            <prime:pieChart
                    id="pieChart"
                    value="#{findingGraphicalReportsController.pieChartModel}"
                    legendPosition="w"
                    title="Findings Graph"
                    style="width:500px;height:400px;"
                    sliceMargin="5"
                    showDataLabels="true"
                    dataFormat="value">
                <prime:ajax event="itemSelect" listener="#{findingGraphicalReportsController.selectPieChart}" update="growl"/>
            </prime:pieChart>

            <p class="text-error" style="width:500px;text-align: center">To see details of the findings please click on the chart</p>
        </div>
    </ui:define>

    <ui:define name="helpContent">
        <b>
        </b>
    </ui:define>

</ui:composition>

src/main/webapp/admin/importFinding.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:prime="http://primefaces.org/ui"
                xmlns:util="http://java.sun.com/jsf/composite/components/common"
                xmlns:sec="http://www.springframework.org/security/tags"
                template="/WEB-INF/templates/default.xhtml">

    <ui:define name="pageHeader">
        Bulk Finding Import From Excel File
    </ui:define>

    <ui:define name="mainContent">
        <h:form enctype="multipart/form-data">
            <h:panelGrid id="panelGrid" columns="2" styleClass="table table-striped table-bordered table-condensed">
                <prime:outputLabel value="File"/>
                <prime:outputPanel>
                    <prime:fileUpload
                            fileUploadListener="#{importFindingController.handleFileUpload}"
                            multiple="false"
                            label="Choose Excel File"
                            required="true"
                            process="@this"
                            auto="true"
                            mode="advanced"
                            update=":growl,panelImportResult"
                            sizeLimit="10485760"
                            allowTypes="/(\.|\/)(xls|xlsx)$/"
                            oncomplete="statusDialog.hide();">
                    </prime:fileUpload>
                </prime:outputPanel>
                <f:facet name="footer">
                    <h:commandLink action="#{importFindingController.exportTemplate()}" value="Generate Excel Template" />
                </f:facet>
            </h:panelGrid>
            <prime:outputPanel id="panelImportResult">
                <prime:outputPanel rendered="#{importFindingController.findingImportWrapperList.size() gt 0}">
                    <util:findingImportList
                            findings="#{importFindingController.findingImportWrapperList}"
                            bean="#{importFindingController}"/>
                </prime:outputPanel>
                <br/>
                <h:panelGroup style="float: right;">
                    <prime:commandButton
                            value="Import Valid Findings"
                            styleClass="btn btn-primary"
                            style="float:right"
                            widgetVar="importButton"
                            rendered="#{importFindingController.findingImportWrapperList.size() gt 0}"
                            actionListener="#{importFindingController.importFindings()}"
                            update="panelImportResult"/>
                </h:panelGroup>
            </prime:outputPanel>
           </h:form>
    </ui:define>

    <ui:define name="helpContent">
        <b>
            At this page you can define new finding and assign it to the specific user or group
        </b>
    </ui:define>

</ui:composition>

src/main/webapp/admin/summaryReport.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:prime="http://primefaces.org/ui"
                template="/WEB-INF/templates/default.xhtml">

    <ui:define name="pageHeader">
        Audit Cockpit
    </ui:define>

    <ui:define name="mainContent">
        <h:form id="summaryReportForm">
            <h:panelGrid id="searchPanel" columns="3" styleClass="table table-striped table-bordered table-condensed">
                <prime:outputLabel for="txtAuditType" value="Audit Type"/>
                <prime:selectOneMenu
                        id="txtAuditType"
                        value="#{summaryReportController.auditType}"
                        converter="entityConverter">
                    <prime:ajax event="change" update="@form" listener="#{summaryReportController.changeAuditType()}"/>
                    <f:selectItems
                            value="#{commonDefinitionsController.auditTypes}"
                            var="_auditType"
                            itemValue="#{_auditType}"
                            itemLabel="#{_auditType.description}"/>
                    <f:selectItem noSelectionOption="true" itemLabel="Please Select" escape="true" itemDisabled="true"/>
                    <f:attribute name="entityList" value="#{commonDefinitionsController.auditTypes}"/>
                </prime:selectOneMenu>
                <prime:tooltip  for="txtAuditType" value="Audit Type" />

                <prime:outputLabel for="txtKpi" value="KPI Rate"/>
                <h:outputText id="txtKpi" value="% #{summaryReportController.kpiRate}" style="color:red;font-weight: bold;"/>
                <prime:tooltip id="toolTipKpi" for="txtKpi" style="color:red;font-size: smaller;">
                    <h:panelGrid columns="2" styleClass="table table-striped table-bordered table-condensed">
                         <h:outputText  value="Verh High + High Findings Rate" />
                         <h:outputText  value="% #{summaryReportController.higherOverdueKPIRate * 100}" />
                         <h:outputText  value="Moderate + Low Findings Rate " />
                         <h:outputText  value="% #{summaryReportController.lowerOverdueKPIRate * 100}" />
                        <f:facet name="footer">
                            <h:outputText value="KPI Rate : % #{summaryReportController.kpiRate}" style="float:right;"/>
                        </f:facet>
                    </h:panelGrid>
                </prime:tooltip>
            </h:panelGrid>
            <prime:spacer height="20" width="20"/>
            <h:panelGrid id="proxyLogGrid" style="width: 100%;" columnClasses="columnVerticalTop">
                <prime:panel style="width: 100%;">
                    <f:facet name="header">
	                   <h:outputText value="Summary Report Graph" />
	                </f:facet>
	                <!--  seriesColors="B40431,FF0000,F7FE2E,088A08"-->
	                <prime:barChart id="graph1"
		               	value="#{summaryReportController.businessSubProcessChatModel}"
		               	legendPosition="ne"
		               	animate="true"
		               	seriesColors="ff0000,ffa500,ffff00,9acd32"
		               	yaxisLabel="RECORDS">
                        <prime:ajax event="itemSelect"
                            process="@this"
                            update=":dlgSummaryForm"
		               	 	listener="#{summaryReportController.summaryReportListener}"
                            oncomplete="dlgSummary.show();"/>
		            </prime:barChart>
            	</prime:panel>
            </h:panelGrid>
        </h:form>
        <h:form id="dlgSummaryForm">
            <prime:dialog id="dlgSummary" header="Summary Report List" position="center" maximizable="false" widgetVar="dlgSummary" style="height:auto;">
                <prime:ajax event="close" update=":dlgSummaryForm" oncomplete="summaryDataTable.getPaginator().setPage(0);"/>
                <prime:dataTable id="summaryDataTable"
                                 value="#{summaryReportController.selectedFindings}"
                                 var="_finding"
                                 rows="5"
                                 paginator="true"
                                 paginatorPosition="bottom"
                                 widgetVar="summaryDataTable"
                                 style="width:100%;text-align: center;">
                    <prime:columnGroup type="header">
                         <prime:row>
                             <prime:column headerText="Finding Number" />
                             <prime:column headerText="Sub Process" />
                             <prime:column headerText="Finding Title"/>
                             <prime:column headerText="Priority"/>
                             <prime:column headerText="Target Date"/>
                             <prime:column headerText="Delay Time (days)"/>
                             <prime:column headerText="Status"/>
                        </prime:row>
                    </prime:columnGroup>
                    <prime:column style="text-align: left;">
                        <h:outputText value="#{_finding.findingNumber}"/>
                    </prime:column>
                    <prime:column style="text-align: left;">

                            <h:outputText value="#{_finding.businessSubProcessType.description}" style="color:#a8a8a8;"/>

                    </prime:column>
                    <prime:column style="text-align: left;">
                        <h:outputText value="#{_finding.description}"/>
                    </prime:column>
                    <prime:column>
                        <h:outputText value="#{_finding.priority.description}"/>
                    </prime:column>
                    <prime:column>
                        <h:outputText value="#{_finding.completionDate}">
                            <f:convertDateTime pattern="dd/MM/yyyy"/>
                        </h:outputText>
                    </prime:column>
                    <prime:column>
                        <h:outputText value="#{_finding.countOfDelayedDay}"/>
                    </prime:column>
                    <prime:column>
                        <h:outputText value="#{_finding.statusOfFinding.description}"/>
                    </prime:column>
                </prime:dataTable>
                <br/>
                <h:commandLink action="#{summaryReportController.exportFindingsToExcel()}"
                               rendered="#{summaryReportController.selectedFindings.size() gt 0}" value="Export to Excel" />
            </prime:dialog>
        </h:form>
    </ui:define>
</ui:composition>