src/main/java/com/tr/aksigorta/denetimtaleptakip/model/User.java
package com.tr.aksigorta.denetimtaleptakip.model;

import com.google.common.collect.Lists;
import com.google.common.collect.Sets;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import org.apache.commons.collections.CollectionUtils;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;
import org.hibernate.envers.RelationTargetAuditMode;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Set;

/**
 * User: dpinar
 * Date: 3/8/17
 * Time: 3:27 PM
 */

@Entity
@Table(name = "dt_id_users_table")
@Data
@ToString(includeFieldNames = true, callSuper = true, exclude = {"findings", "adminUser", "responsibleBusinessTypes", "responsibleBusinessSubTypes"})
@EqualsAndHashCode(callSuper = true, of = {"username"})
@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
public class User extends BaseEntity implements Serializable
{
    @Column(name = "username")
    private String username;
    @Column(name = "email")
    private String email;
    @Column(name = "name_surname")
    private String nameSurname;
    @Column(name = "job_title")
    private String jobTitle;
    @Column(name = "ACTIVE", columnDefinition = "BIT", length = 1)
    private boolean active = true;
    @ManyToOne
    @JoinColumn(name = "ADMIN_USER_ID")
    private User adminUser;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EDIT_DATE")
    private Date editDate;

    @OneToMany(mappedBy = "actionOwner")
    private Set<FindingAction> findings = Sets.newHashSet();

    @ManyToMany(mappedBy = "responsibleHeads", fetch = FetchType.LAZY)
    private Set<BusinessProcessType> responsibleBusinessTypes = Sets.newHashSet();

    @ManyToMany(mappedBy = "responsibleHeads", fetch = FetchType.LAZY)
    private Set<BusinessSubProcessType> responsibleBusinessSubTypes = Sets.newHashSet();

    @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinTable(
            name = "DT_ID_USER_ROLES_TABLE",
            joinColumns =
            @JoinColumn(name = "USER_ID", referencedColumnName = "ID"),
            inverseJoinColumns =
            @JoinColumn(name = "ROLE_ID", referencedColumnName = "ID")
    )
    @Fetch(FetchMode.SUBSELECT)
    @NotAudited
    private Set<Role> roles = Sets.newHashSet();

    @Transient
    public static List<String> usersEmailAddresses(Collection<User> users)
    {
        List<String> emailAddresses = Lists.newArrayList();
        for (User user : users)
        {
        	if(user.isActive())	// kullanıcı aktif ise mail listesine ekle 
        		emailAddresses.add(user.getEmail());
        }
        return emailAddresses;
    }

    @Transient
    public static List<String> usersNamesAndSurnames(Collection<User> users)
    {
        List<String> namesAndSurname = Lists.newArrayList();
        for (User user : users)
        {
            namesAndSurname.add(user.getNameSurname());
        }
        return namesAndSurname;
    }

    @Transient
    public boolean isUserReponsibleOfAnyBusinessType()
    {
        return CollectionUtils.isNotEmpty(getResponsibleBusinessTypes()) || CollectionUtils.isNotEmpty(getResponsibleBusinessSubTypes());
    }

    @Transient
    public boolean hasRole(String roleName)
    {
        for (Role role : getRoles())
        {
            if (role.getName().equals(roleName))
            {
                return true;
            }
        }
        return false;
    }

    @Transient
    public List<Role> getRolesAsList()
    {
        return Lists.newLinkedList(getRoles());
    }

}

src/main/webapp/WEB-INF/templates/default.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
      xmlns:prime="http://primefaces.org/ui"
      xmlns:sec="http://www.springframework.org/security/tags">
<h:head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="Pragma" content="no-cache"/>
    <meta http-equiv="Cache-Control" content="no-cache"/>
    <meta http-equiv="Expires" content="0"/>
    <meta http-equiv="Last-Modified" content="0" />
    <meta http-equiv="Cache-Control" content="no-cache, mustrevalidate" />
    <title><ui:insert name="title">Çimsa Audit Follow Up System (AFUS)</ui:insert></title>
    <link href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap.css" rel="stylesheet" type="text/css"/>
    <link href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>
    <link href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap-aks.css" rel="stylesheet" type="text/css"/>
    <link href="#{facesContext.externalContext.requestContextPath}/favicon.ico" rel="icon" />
    <script src="#{facesContext.externalContext.requestContextPath}/style/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js" type="text/javascript"></script>
    <!-- <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script> -->
</h:head>

<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <h:form>
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <h:commandLink styleClass="brand" value="Çimsa Audit Follow Up System (AFUS)" action="#{authenticationController.redirectUserToWelcomePage}"/>

                <div class="nav-collapse collapse">
                    <p class="navbar-text pull-right">
                        <h:commandLink value="Logout (#{visit.user.nameSurname})" action="#{authenticationController.logout}" style="color:#f5f5f5;font-size: 11px;"/>
                    </p>
                    <ul class="nav">
                        <li>
                            <!-- <h:link value="My Tasks" rendered="#{sec:areAnyGranted('ROLE_USER')}" outcome="/users/userTasks.xhtml"/>  -->
                            <h:link value="My Tasks" outcome="/users/userTasks.xhtml"/>
                        </li>
                        <li>
                            <!-- <h:link value="My Department Tasks" rendered="#{sec:areAnyGranted('ROLE_USER, ROLE_ADMIN') and visit.user.userReponsibleOfAnyBusinessType}"
                                    outcome="/users/departmentFindings.xhtml"/> -->
                            <h:link value="My Department Tasks" outcome="/users/departmentFindings.xhtml"/>
                        </li>
                        <li>
                            <!-- <h:link value="Finding List" rendered="#{sec:areAnyGranted('ROLE_ADMIN, ROLE_READONLY')}" outcome="/admin/findingAdmin.xhtml"/> -->
                            <h:link value="Finding List" outcome="/admin/findingAdmin.xhtml"/>
                        </li>
                        <li>
                        	<!-- <h:link value="Search" rendered="#{sec:areAnyGranted('ROLE_ADMIN, ROLE_USER, ROLE_READONLY')}" outcome="/admin/searchFinding.xhtml"/> -->
                            <h:link value="Search" outcome="/admin/searchFinding.xhtml"/>
                        </li>
                        <!-- <h:panelGroup rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"> -->
                        <h:panelGroup>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Finding
                                    <b class="caret"/>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                    	<!-- <h:link value="New" rendered="#{sec:areAnyGranted('ROLE_ADMIN')}" outcome="/admin/editFinding.xhtml"/> -->
                                        <h:link value="New" outcome="/admin/editFinding.xhtml"/>
                                    </li>
                                    <li>
                                    	<!-- <h:link value="Excel Import" rendered="#{sec:areAnyGranted('ROLE_ADMIN')}" outcome="/admin/importFinding.xhtml"/> -->
                                        <h:link value="Excel Import" outcome="/admin/importFinding.xhtml"/>
                                    </li>
                                </ul>
                            </li>
                        </h:panelGroup>
                        <!-- <h:panelGroup rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"> -->
                        <h:panelGroup>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Administration
                                    <b class="caret"/>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                    	<!-- <h:link value="User Administration" rendered="#{sec:areAnyGranted('ROLE_ADMIN')}" outcome="/admin/userAdmin.xhtml"/> -->
                                        <h:link value="User Administration" outcome="/admin/userAdmin.xhtml"/>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a tabindex="-1" href="#">Audit and Main Process Administration</a>
                                        <ul class="dropdown-menu">
                                            <li>
                                            	<!-- <h:link
                                                        value="Audit Type Administration"
                                                        rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"
                                                        outcome="/admin/auditTypesAdmin.xhtml"/> -->
                                                <h:link
                                                        value="Audit Type Administration"
                                                        outcome="/admin/auditTypesAdmin.xhtml"/>
                                            </li>
                                            <li>
                                            	<!-- <h:link
                                                        value="Main Process Administration"
                                                        rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"
                                                        outcome="/admin/businessTypesAdmin.xhtml"/> -->
                                                <h:link
                                                        value="Main Process Administration"
                                                        outcome="/admin/businessTypesAdmin.xhtml"/>
                                            </li>
                                            <li>
                                            	<!-- <h:link
                                                        value="View All in Once"
                                                        rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"
                                                        outcome="/admin/auditAndBusinessTypesViewAll.xhtml"/> -->
                                                <h:link
                                                        value="View All in Once"
                                                        outcome="/admin/auditAndBusinessTypesViewAll.xhtml"/>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </h:panelGroup>
                        <!-- <h:panelGroup rendered="#{sec:areAnyGranted('ROLE_ADMIN')}"> -->
                        <h:panelGroup>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Reports
                                    <b class="caret"/>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                    	<!-- <h:link
                                                value="Number of Findings per Status Graph"
                                                rendered="#{sec:areAnyGranted('ROLE_ADMIN, ROLE_READONLY')}"
                                                outcome="/admin/numberOfFindingsPerStatusGraphicalReport.xhtml"/> -->
                                        <h:link
                                                value="Number of Findings per Status Graph"
                                                outcome="/admin/numberOfFindingsPerStatusGraphicalReport.xhtml"/>
                                    </li>
                                    <li>
                                    	<!-- <h:link
                                                value="Number of Findings per Company Graph"
                                                rendered="#{sec:areAnyGranted('ROLE_ADMIN, ROLE_READONLY')}"
                                                outcome="/admin/numberOfFindingsPerCompanyGraphicalReport.xhtml"/> -->
                                        <h:link
                                                value="Number of Findings per Company Graph"
                                                outcome="/admin/numberOfFindingsPerCompanyGraphicalReport.xhtml"/>
                                    </li>
                                    <li>
                                    	<!-- <h:link
                                                value="Number of Findings per Year Graph"
                                                rendered="#{sec:areAnyGranted('ROLE_ADMIN, ROLE_READONLY')}"
                                                outcome="/admin/numberOfFindingsPerYearGraphicalReport.xhtml"/> -->
                                        <h:link
                                                value="Number of Findings per Year Graph"
                                                outcome="/admin/numberOfFindingsPerYearGraphicalReport.xhtml"/>
                                    </li>
                                </ul>
                            </li>
                        </h:panelGroup>
                        
                        <li>
                        	<!-- <h:outputLink value="#{facesContext.externalContext.requestContextPath}/documents/Help_Dokumani.pdf" rendered="#{sec:areAnyGranted('ROLE_ADMIN, ROLE_USER, ROLE_READONLY')}"  target="_document">
                                Help
                            </h:outputLink> -->
                            <h:outputLink value="#{facesContext.externalContext.requestContextPath}/documents/Help_Dokumani.pdf" target="_document">
                                Help
                            </h:outputLink>
                        </li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </h:form>
        </div>
    </div>
</div>

<prime:growl id="growl" showDetail="false" sticky="true" autoUpdate="true"/>

<prime:ajaxStatus onstart="statusDialog.show();" onsuccess="statusDialog.hide();"/>

<prime:dialog
        modal="true"
        widgetVar="statusDialog"
        header="Please Wait"
        draggable="false"
        closable="false"
        resizable="false">
    <prime:graphicImage value="/images/ajaxloadingbar.gif"/>
</prime:dialog>

<!-- /container -->

<div class="container">

    <div class="content">
        <div class="page-header">
            <h5>
                <ui:insert name="pageHeader"/>
            </h5>
        </div>
        <div class="row">
            <div class="span12">
                <ui:insert name="mainContent"/>
            </div>
        </div>
    </div>

    <footer>
        <p>
            Bu sistemin mülkiyeti Çimsa’ya aittir ve şirkete özel, gizli bilgiler içermektedir. Bu bilgiler Çimsa dışı kullanılamaz ve paylaşılamaz. Bilgilerin güvenliği ve gizliliği kullanıcıların sorumluluğundadır.
            <br />
            This system belongs to Çimsa and contains confidentialand privileged information. This information can not be shared or disclosed outside the Company. Information security and confidentiality are the obligation of the system users.
        </p>
    </footer>

</div>
<!-- /container -->
</body>
</html>

src/main/webapp/WEB-INF/templates/noLinksTemplate.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
      xmlns:prime="http://primefaces.org/ui">
<h:head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="Pragma" content="no-cache"/>
    <meta http-equiv="Cache-Control" content="no-cache"/>
    <meta http-equiv="Expires" content="0"/>
    <meta http-equiv="Last-Modified" content="0" />
    <meta http-equiv="Cache-Control" content="no-cache, mustrevalidate" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title><ui:insert name="title">Çimsa Audit Follow Up System (AFUS) v#{initParam['appVersion']}</ui:insert></title>
    <link href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap.css" rel="stylesheet" type="text/css"/>
    <link href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>
    <link href="#{facesContext.externalContext.requestContextPath}/style/css/bootstrap-aks.css" rel="stylesheet" type="text/css"/>
    <link href="#{facesContext.externalContext.requestContextPath}/favicon.ico" rel="icon" />
    <script src="#{facesContext.externalContext.requestContextPath}/style/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script> -->
</h:head>

<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span
                    class="icon-bar"></span>
            </a> <a class="brand" href="#">Çimsa Audit Follow Up System (AFUS) v#{initParam['appVersion']}</a>
        </div>
    </div>
</div>

<prime:growl id="growl" showDetail="false" sticky="true"/>

<!-- /container -->

<div class="container">

    <div class="content">
        <div class="row">
            <div class="span2 offset4">
                <h:form>
                    <ui:insert name="mainContent"/>
                </h:form>
            </div>
        </div>
    </div>

    <footer>
        <p>Çimsa 2017</p>
    </footer>

</div>
<!-- /container -->
</body>
</html>